POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Testaaja",
  "dateOfBirth": "1990-02-22",
  "ssn": "123456-1234",
  "gender": "male",
  "occupation": "developer"
}