POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Ipan matkassa",
    "author": "Pena",
    "likes": 10,
    "url": "http://Penanblogi.fi",
    "userId": "65a7c7e7ef073a2072754aef"
}